import json
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional
from aura.server.db import get_wishlist_items

@dataclass
class RootCause:
    id: str
    rule_id: str
    category: str
    severity: str
    title: str
    affected_elements: List[str]
    count: int
    evidence_sample: Dict[str, Any]
    css_patch: Optional[str] = None
    html_patch: Optional[str] = None
    effort: str = "low" # "low" | "medium" | "high"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

class BatchRemediationEngine:
    """Clusters wishlist and run findings by root-cause pattern and generates unified multi-artifact patch bundles."""

    def cluster_findings(self, findings: List[Dict[str, Any]]) -> List[RootCause]:
        """Clusters findings by (rule_id, element_role)."""
        clusters: Dict[str, List[Dict[str, Any]]] = {}

        for f in findings:
            rule_id = f.get("rule_id", "unknown")
            role = f.get("element", {}).get("role", "elem")
            cluster_key = f"{rule_id}::{role}"
            
            if cluster_key not in clusters:
                clusters[cluster_key] = []
            clusters[cluster_key].append(f)

        root_causes: List[RootCause] = []
        for idx, (key, group) in enumerate(clusters.items(), start=1):
            rule_id, role = key.split("::", 1)
            first = group[0]
            affected = [g.get("element", {}).get("name", "element") for g in group]
            count = len(group)

            # Synthesize patches based on rule
            css_patch, html_patch, effort = self._synthesize_patch(rule_id, role, affected, first)

            root_causes.append(RootCause(
                id=f"RC-{idx:02d}",
                rule_id=rule_id,
                category=first.get("category", "a11y"),
                severity=first.get("severity", "minor"),
                title=f"Fix {first.get('title', rule_id)} across {count} instance(s)",
                affected_elements=list(set(affected))[:5],
                count=count,
                evidence_sample=first.get("evidence", {}),
                css_patch=css_patch,
                html_patch=html_patch,
                effort=effort
            ))

        return root_causes

    def _synthesize_patch(self, rule_id: str, role: str, affected: List[str], sample: Dict[str, Any]) -> tuple:
        if "contrast" in rule_id:
            css = "/* Fix color contrast to satisfy WCAG AA 4.5:1 ratio */\n.nav-links a, .product-price {\n  color: #0f172a !important;\n  background-color: #ffffff !important;\n}"
            html = "<!-- Contrast fix: replace light gray text classes with dark contrast classes -->\n<a href=\"#\" class=\"text-slate-900\">High Contrast Link</a>"
            return css, html, "low"

        if "touch-target" in rule_id:
            css = "/* Ensure touch targets meet minimum 48px hit area */\nbutton, .btn-add-tiny, .btn-checkout, .icon-btn {\n  min-width: 48px !important;\n  min-height: 48px !important;\n  padding: 10px 16px !important;\n  border-radius: 8px !important;\n}"
            html = "<!-- Wrap button or expand padding for 48px target -->\n<button class=\"min-h-[48px] min-w-[48px] p-3 ...\">Add to Cart</button>"
            return css, html, "low"

        if "missing-accessible-name" in rule_id:
            css = None
            html = "<!-- Add explicit aria-label to icon buttons -->\n<button class=\"icon-btn\" aria-label=\"Search Catalog\">\n  <svg aria-hidden=\"true\">...</svg>\n</button>"
            return css, html, "medium"

        if "occluded-control" in rule_id:
            css = "/* Prevent floating promotional modals from obstructing interactive controls */\n.occluding-modal {\n  pointer-events: none;\n}\n.occluding-modal > * {\n  pointer-events: auto;\n}"
            html = "<!-- Place banner inside standard layout stream instead of floating overlay -->\n<div class=\"promo-banner static-container\">...</div>"
            return css, html, "medium"

        if "cognitive" in rule_id or "dyslexia" in rule_id:
            css = "/* Improve readability and cognitive processing */\n.terms-wall {\n  font-size: 15px !important;\n  line-height: 1.6 !important;\n  text-align: left !important;\n  max-width: 65ch !important;\n}"
            html = "<!-- Use clear, concise language with bullet points -->\n<p class=\"readable-prose\">Returns accepted within 30 days for full refund.</p>"
            return css, html, "medium"

        return None, None, "low"

    def generate_bundle(self, root_causes: List[RootCause]) -> Dict[str, str]:
        """Generates fixes.css, aria-patches.md, remediation.md, and findings.json."""
        css_blocks = []
        html_blocks = []
        markdown_lines = [
            "# AURA Automated Remediation Action Plan",
            "",
            "> Generated by AURA Autonomous Testing Framework from bookmarked wishlist items.",
            "",
            "## Summary of Clustered Root Causes",
            ""
        ]

        for rc in root_causes:
            markdown_lines.append(f"### [{rc.id}] {rc.title} ({rc.severity.upper()})")
            markdown_lines.append(f"- **Rule**: `{rc.rule_id}`")
            markdown_lines.append(f"- **Instances Clustered**: {rc.count}")
            markdown_lines.append(f"- **Estimated Effort**: {rc.effort.capitalize()}")
            markdown_lines.append(f"- **Evidence**: `{json.dumps(rc.evidence_sample)}`")
            markdown_lines.append(f"- **Affected Controls**: {', '.join(rc.affected_elements)}")
            markdown_lines.append("")

            if rc.css_patch:
                css_blocks.append(f"/* === {rc.id}: {rc.title} === */\n{rc.css_patch}\n")
            if rc.html_patch:
                html_blocks.append(f"### {rc.id}: {rc.title}\n```html\n{rc.html_patch}\n```\n")

        markdown_lines.append("## HTML & ARIA Patch Snippets")
        markdown_lines.extend(html_blocks)

        fixes_css = "\n".join(css_blocks) if css_blocks else "/* No CSS overrides needed */"
        aria_patches_md = "\n".join(html_blocks) if html_blocks else "No ARIA patches generated."
        remediation_md = "\n".join(markdown_lines)
        findings_json = json.dumps([rc.to_dict() for rc in root_causes], indent=2)

        return {
            "fixes_css": fixes_css,
            "aria_patches_md": aria_patches_md,
            "remediation_md": remediation_md,
            "findings_json": findings_json
        }

remediation_engine = BatchRemediationEngine()
